fastlane_version '2.53.1'
 
before_all do
  ensure_git_status_clean
  git_pull
end
 
platform :ios do
   # iOS Lanes
   desc 'Fetch certificates and provisioning profiles'
    lane :certificates do
    match(app_identifier: 'com.nigelrudolf.awesomeproject', type: 'development', readonly: true)
    match(app_identifier: 'com.nigelrudolf.awesomeproject', type: 'appstore', readonly: true)
end
end
 
platform :android do
  # Android Lanes
end